apiVersion: 1

datasources:
  - name: PAREX PostgreSQL
    uid: parex-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: parex
    isDefault: true
    editable: false

    secureJsonData:
      password: parex_local

    jsonData:
      database: parex
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false